### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by SageStarCodes**
Make package.json adhere to the npm documentation by specifying license as `SEE LICENSE IN <filename>` and also bump the version for dev.

### CODE REVIEW

**Comment by m00nwtchr** [comment]
I don't get what is wrong with just specifying the license. `npm init` even just puts the license into the package.json

**Comment by m00nwtchr** [comment]
Also "SEE LICENSE IN LICENSE" sounds supid XD

**Comment by SageStarCodes** [comment]
but we are using a license file so it should be specified to see the license in the file, this also makes FOSSA happy

**Comment by SageStarCodes** [comment]
ok, you are right... I misunderstood the documentation, it should stay GPL-3.0

**Pull request merged**
