### PR TITLE
Rewrite the bot in TypeScript

### PR DESCRIPTION
**Pull request by SageStarCodes**
TypeScript allows for cleaner code, abstraction and type checking, I rewrote the bot so that we can take advantages of these features.

### CODE REVIEW

**Review by m00nwtchr — DISMISSED** [review]
You can just do `npm i --save typescript` and it will install it automatically

**Comment by SageStarCodes** [comment]
@lukas2005 There are some issues doing this, TypeScript is best installed globally. Just as for example firebase-cli

**Comment by m00nwtchr** [comment]
@D3add3d what issues? Also installing ANYTHING like typescript, webpack, etc. is NEVER good.
For example, if a developer has a project using a different version of typescript than this one

**Comment by m00nwtchr** [comment]
@D3add3d this might help ya: https://stackoverflow.com/questions/38030078/how-to-install-and-run-typescript-locally-in-npm

**Comment by SageStarCodes** [comment]
@lukas2005 that's exactly what I was talking about... feels like a dirty hack

**Comment by SageStarCodes** [comment]
besides... does it really bother you that much that you have to run one more command?

**Comment by m00nwtchr** [comment]
@D3add3d I'm not saying that I don't like having to run one more command but that installing typescript globally can cause serious issues (mainly for contributors altho not fully) in the future. And why a dirty hack?

**Comment by SageStarCodes** [comment]
Installing it globally is the recommended way, why would it cause issues?

**Comment by m00nwtchr** [comment]
Well, I already posted one example. Another one: without the `--save-dev` option the info about the version of typescript you are using is lost - meaning that if a breaking change will occur in typescript and someone will just `npm install typescript -g` then the bot will crash

**Review by m00nwtchr — APPROVED** [review]

**Pull request merged**
